
default: all


all: extract 


extract:
	python /home/sypeng/soft/alamode/alamode-20241218/tools/extract.py --QE=/home/sypeng/work/silicon/alamode-PBE-prim/prim-444/2_anharmonic_3rd/data/si444-prim.pw.in samples/*/scf.out > DFSET_harmonic
