# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

export LC_CTYPE=en_US.UTF-8
export LANG=en_US.UTF-8

#module part
#module add mpi/intelmpi/2017.4.239


# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
#export PYTHONPATH=/public/home/sypeng/Source/pylibwyl:$PYTHONPATH
export PYTHONPATH=/public/home/sypeng/UFlib:$PYTHONPATH
# added by Anaconda3 installer
# export PATH="/public/home/sypeng/anaconda3/bin:$PATH"  # commented out by conda initialize
export PATH="/public/home/sypeng/soft/wannier_tools/bin:$PATH"
export PATH="/public/home/sypeng/soft/grace-5.1.25/src:$PATH"
#export PATH="/public/home/sypeng/soft/wannier90-2.1.0:$PATH"
export PATH="/public/home/sypeng/soft/wannier90-3.0.0:$PATH"
export PATH="/public/home/sypeng/soft/wannier90-3.0.0/utility:$PATH"
export LIBRARY_PATH=/public/home/sypeng/soft/wannier90-3.0.0:$LIBRARY_PATH
# alias
alias ssqstat="squeue -u sypeng"
alias tarz="tar -czvf"
alias taruz="tar -xzvf"
alias sid="sacct | grep"
alias logdir="/public/home/sypeng/LOG/qs.dat"
#alias qstat="for ((i=1;i<81;i=i+1));do echo -n '-' >> /public/home/sypeng/LOG/qs.dat;done;echo '' >> /public/home/sypeng/LOG/qs.dat;echo `date +'%Y-%m-%d %H:%M:%S'` >> /public/home/sypeng/LOG/qs.dat;for ((i=1;i<41;i=i+1));do echo -n '-' >> /public/home/sypeng/LOG/qs.dat;done;echo '' >> /public/home/sypeng/LOG/qs.dat;squeue -u sypeng | tee -a /public/home/sypeng/LOG/qs.dat | more;for ((i=1;i<61;i=i+1));do echo -n '-' ;done;echo '';for ((i=1;i<41;i=i+1));do echo -n '-' >> /public/home/sypeng/LOG/qs.dat;done;echo '' >> /public/home/sypeng/LOG/qs.dat;for id in \$(squeue -u sypeng | tail -n +2 | awk '{print \$1}');do ssid='slurm-'\$"id"'.out';find /public/home/sypeng/work -name \$ssid | tee -a /public/home/sypeng/LOG/qs.dat | more ;done;for ((i=1;i<81;i=i+1));do echo -n '-' >> /public/home/sypeng/LOG/qs.dat;done;echo '' >> /public/home/sypeng/LOG/qs.dat"
alias qstatt="bash /public/home/sypeng/func_myself/qstatjob.sh"
alias vil="vi ~/LOG/qs.dat"
alias scpfile="bash /public/home/sypeng/func_myself/scpfile.sh"
alias checkgutz="bash /public/home/sypeng/func_myself/checkgutzjob.sh"
alias rm="bash /public/home/sypeng/func_myself/xxyrm.sh"
#alias cp="bash /public/home/sypeng/func_myself/sypcp.sh"
alias sline="bash /public/home/sypeng/func_myself/showline.sh"
export PATH=/public/home/sypeng/soft/vaspkit.0.73/bin:${PATH}
export PATH=/public/software/compiler/intel/parallel_studio_xe_2019_update3/bin:$PATH
export PATH=/public/home/sypeng/soft/mpich-install/bin:${PATH}
export LD_LIBRARY_PATH=/public/software/compiler/intel/parallel_studio_xe_2019_update3/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/public/software/compiler/intel/parallel_studio_xe_2019_update3/mkl/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/public/home/sypeng/soft/mpich-install/lib:$LD_LIBRARY_PATH
#export LD_LIBRARY_PATH=/usr/lib64:$LD_LIBRARY_PATH
#export PATH=/public/home/sypeng/intel/compilers_and_libraries_2018.5.274/linux/mpi/intel64/bin:${PATH}
#export MKLROOT=/public/software/compiler/intel/parallel_studio_xe_2019_update3/mkl
#source /public/software/profile.d/compiler_intel-compiler-2019u3.sh
#source /public/software/profile.d/mpi_intelmpi-2019u3.sh
#source /public/software/compiler/intel/parallel_studio_xe_2019_update3/bin/compilervars.sh intel64
# --- BERRYPI START ---
export BERRYPI_PATH=$WIENROOT/SRC_BerryPI/BerryPI
export BERRYPI_PYTHON=/usr/bin/python2.7
alias berrypi="${BERRYPI_PYTHON} ${BERRYPI_PATH}/berrypi"
# --- BERRYPI END ---
# added by WIEN2k: BEGIN
# --------------------------------------------------------
alias lsi="ls -aslp *.in*"
alias lso="ls -aslp *.output*"
alias lsd="ls -aslp *.def"
alias lsc="ls -aslp *.clm*"
alias lss="ls -aslp *.scf* */*.scf"
alias lse="ls -aslp *.error"
alias LS="ls -aslp | grep /"
alias pslapw="ps -ef |grep "lapw""
alias cdw="cd /public/home/sypeng/WIEN2k"
export OMP_NUM_THREADS=1
#export LD_LIBRARY_PATH=.....
export EDITOR="vim"
export SCRATCH=./
export WIENROOT=/public/home/sypeng/soft/wien2k-install
export W2WEB_CASE_BASEDIR=/public/home/sypeng/WIEN2k
export STRUCTEDIT_PATH=$WIENROOT/SRC_structeditor/bin
export PDFREADER=acroread
export PATH=$WIENROOT:$STRUCTEDIT_PATH:$WIENROOT/SRC_IRelast/script-elastic:$PATH:.
export OCTAVE_EXEC_PATH=${PATH}::
export OCTAVE_PATH=${STRUCTEDIT_PATH}::


# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/public/home/sypeng/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/public/home/sypeng/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/public/home/sypeng/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/public/home/sypeng/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<


#


export PATH=/public/home/sypeng/intel/bin:$PATH
export PATH=/public/home/sypeng/intel/compilers_and_libraries_2018.5.274/linux/mpi/intel64/bin/:$PATH
export LD_LIBRARY_PATH=/public/home/sypeng/intel/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/public/home/sypeng/intel/mkl/lib:$LD_LIBRARY_PATH
export LIBRARY_PATH=/public/home/sypeng/intel/mkl/lib/intel64_lin/:$LIBRARY_PATH
source /public/home/sypeng/intel/impi/2018.4.274/intel64/bin/mpivars.sh
export LD_LIBRARY_PATH=/public/home/sypeng/intel/lib/intel64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/public/home/sypeng/intel/compilers_and_libraries_2018.5.274/linux/mpi/intel64/lib:$LD_LIBRARY_PATH
export LIBRARY_PATH="/public/home/sypeng/intel/compilers_and_libraries_2018.5.274/linux/compiler/lib/intel64:$LIBRARY_PATH"
#
source /public/home/sypeng/intel/compilers_and_libraries_2018.5.274/linux/bin/compilervars.sh intel64
source /public/home/sypeng/intel/compilers_and_libraries_2018.5.274/linux/bin/iccvars.sh intel64
source /public/home/sypeng/intel/compilers_and_libraries_2018.5.274/linux/bin/ifortvars.sh intel64
export LD_LIBRARY_PATH=/public/home/sypeng/intel/compilers_and_libraries_2018.5.274/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/public/home/sypeng/intel/compilers_and_libraries_2018.5.274/mkl/lib:$LD_LIBRARY_PATH
export MKLROOT=/public/home/sypeng/intel/mkl

export PATH=$PATH:$WIENROOT:.
ulimit -s unlimited
alias octave="octave -p $OCTAVE_PATH"
# --------------------------------------------------------
# added by WIEN2k: END 
# --- BERRYPI START ---
export BERRYPI_PATH=$WIENROOT/SRC_BerryPI/BerryPI
export BERRYPI_PYTHON=/usr/bin/python2.7
alias berrypi="${BERRYPI_PYTHON} ${BERRYPI_PATH}/berrypi"
# --- BERRYPI END ---

#mpich 3.3.1
export PATH=/public/home/sypeng/soft/mpich-install/bin:$PATH
export LD_LIBRARY_PATH=/public/home/sypeng/soft/mpich-install/lib:$LD_LIBRARY_PATH
export C_INCLUDE_PATH=/public/home/sypeng/soft/mpich-install/include/:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=/public/home/sypeng/soft/mpich-install/include/:$CPLUS_INCLUDE_PATH

#rtgw2020 dylib
export PYTHONPATH=/public/home/sypeng/work/rtgw_imp/gutz:$PYTHONPATH

# fix error in python extension with fortran and mpi
#export LD_PRELOAD=$CONDA_PREFIX/libmkl_core.so:$CONDA_PREFIX/libmkl_sequential.so

# elk
elk_spg=/public/home/sypeng/soft/elk-6.3.2/src/spacegroup/spacegroup
elk=/public/home/sypeng/soft/elk-6.3.2/src/elk


# ASE
#export PYTHONPATH=/public/home/sypeng/.local/lib/python3.7/site-packages/:$PYTHONPATH
#export PATH=/public/home/sypeng/.local/bin/:$PATH

# Fleur for ase
export FLEUR_INPGEN=/public/home/sypeng/soft/fleur3/build/inpgen
#export FLEUR="mpirun -np 35 -host localhost /public/home/sypeng/soft/fleur3/build/fleur_MPI"
export FLEUR="mpirun -np 1 -host localhost /public/home/sypeng/soft/fleur3/build/fleur_MPI"
#export juDFT_MPI='mpirun -np 1 -host localhost'
export FLEUR_SERIAL=/public/home/sypeng/soft/fleur3/build/fleur

# LIBxc
export LIBRARY_PATH=/public/home/sypeng/soft/libxc-install/lib:$LIBRARY_PATH
export C_INCLUDE_PATH=/public/home/sypeng/soft/libxc-install/include:$C_INCLUDE_PATH
export LD_LIBRARY_PATH=/public/home/sypeng/soft/libxc-install/lib:$LD_LIBRARY_PATH

#Blas(original without optimization)
export LIBRARY_PATH=/public/home/sypeng/soft/BLAS-3.8.0:$LIBRARY_PATH

#hdf5
export LIBRARY_PATH=/public/home/sypeng/soft/hdf5-install/lib:$LIBRARY_PATH
export LD_LIBRARY_PATH=/public/home/sypeng/soft/hdf5-install/lib:$LD_LIBRARY_PATH

#fftw3
export LD_LIBRARY_PATH=/public/home/sypeng/soft/fftw3-install/lib/:$LD_LIBRARY_PATH
export LIBRARY_PATH=/public/home/sypeng/soft/fftw3-install/lib/:$LD_LIBRARY_PATH

#Fleur release 3 of v2.7
#export PATH=/public/home/sypeng/soft/fleur3/build/:$PATH

#szlib
export LD_LIBRARY_PATH=/public/home/sypeng/soft/szip-install/lib/:$LD_LIBRARY_PATH

#qe
export PATH=/public/home/sypeng/soft/q-e-qe-6.5/bin:$PATH

#lapack
export LIBRARY_PATH=/public/home/sypeng/soft/lapack-3.8.0:$LIBRARY_PATH

#scalapack
export LIBRARY_PATH=/public/home/sypeng/soft/scalapack-2.1.0:$LIBRARY_PATH

#spex
export PATH=/public/home/sypeng/soft/spex-install/bin:$PATH

#Fleur release 3 of v2.7
export PATH=/public/home/sypeng/soft/fleur3/build/:$PATH
#export juDFT_MPI='mpirun -np 2 -host localhost'


# pgi
export PATH=$HOME/soft/pgi-install2/linux86-64/2019/bin:$PATH
export LD_LIBRARY_PATH=$HOME/soft/pgi-install2/linux86-64/2019/lib:$LD_LIBRARY_PATH

export PATH=/public/home/sypeng/soft/pgi-install2/linux86-64/2019/cuda/10.0/bin/:$PATH
#export PATH=/public/home/sypeng/soft/pgi-install2/linux86-64-llvm/2019/cuda/10.0/bin/:$PATH
export LD_LIBRARY_PATH=/public/home/sypeng/soft/pgi-install2/linux86-64/2019/cuda/10.0/lib64/:$LD_LIBRARY_PATH
#export LD_LIBRARY_PATH=/public/home/sypeng/soft/pgi-install2/linux86-64-llvm/2019/cuda/10.0/lib64/:$LD_LIBRARY_PATH

#pgi-openmpi
export PATH=$HOME/soft/pgi-openmpi-cuda-install/bin:$PATH
export LD_LIBRARY_PATH=$HOME/soft/pgi-openmpi-cuda-install/lib/:$LD_LIBRARY_PATH
#export PATH=/public/home/sypeng/soft/pgi-install2/linux86-64/2019/mpi/openmpi-3.1.3/bin:$PATH
#export LD_LIBRARY_PATH=/public/home/sypeng/soft/pgi-install2/linux86-64/2019/mpi/openmpi-3.1.3/lib:$LD_LIBRARY_PATH

export CUDA_HOME=/public/home/sypeng/soft/pgi-install2/linux86-64/2019/cuda/10.0

# chuangchen
#export CUDADIR=/public/home/sypeng/soft/pgi-install2/linux86-64/2019/cuda/10.0
export CUDADIR=/public/home/sypeng/soft/cuda
export MKLROOT2=/public/home/sypeng/intel/mkl/lib/intel64
export MAGMALIB=/public/home/sypeng/soft/icc-magma-install/lib
export MAGMAINC=/public/home/sypeng/soft/icc-magma-install/include
